### ISSUE TITLE
ctrl+shift+o go to symbol support ?

### ISSUE THREAD

**Issue by oglops** [artbycrunk/vscode-maya#11]
**Is your feature request related to a problem? Please describe.**
When scrubbing long files, a go to symbol feature might be handy

**Describe the solution you'd like**
support it like other languages

**Describe alternatives you've considered**

**Additional context**

**Comment by artbycrunk** [comment]
@oglops  I have added support for symbols in the extension version 1.4.0, so ctrl+shift+o should show a lists of all the symbols in the current file.
can you give it a try and let me know if you have any issues.
