### ISSUE TITLE
Error: line 1: Could not create command port: localhost:7001 (name is invalid).

### ISSUE THREAD

**Issue by BigToeProductions** [artbycrunk/vscode-maya#13]
**Describe the bug**
When trying to open the port on Mac OS with Maya LT, I receive this error.
Error: line 1: Could not create command port: localhost:7001 (name is invalid).

**To Reproduce**
1) Open the script editor:
Run this command: 
commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Maya LT 2020 and Maya LT 2019

I feel like if the port was already in use, I could find a workaround, but the name is invalid is weird for me.  

Thanks in advance.

**Comment by artbycrunk** [comment]
Hmm interesting.. have you tried if this works?

commandPort -name ":7001" -sourceType "mel" -echoOutput;

**Comment by artbycrunk** [comment]
Closing this issue, since there was no response, 
Please reopen if you still have this issue.
