### ISSUE TITLE
Output line numbers are off by 1

### ISSUE THREAD

**Issue by riandrake** [artbycrunk/vscode-maya#14]
**Describe the bug**
In the output window, for Code or for Maya, whenever line numbers are mentioned for python scripts they are always off by 1.

**To Reproduce**
1. Open a new python script
2. Type `asdasdasd`
3. Send script to Maya
4. Read output line number and compare to line number in script

**Expected behavior**
The line numbers should match

**Screenshots**
![image](https://user-images.githubusercontent.com/5866058/78094432-07205380-7431-11ea-967c-f8a7d7c20077.png)

**Additional context**
It's because of the utf8 encoding header written to MayaCode.py

**Comment by artbycrunk** [comment]
@riandrake thanks for reporting this, it has been fixed in the latest release.
