### ISSUE TITLE
how to get the flag info showing on autocomplete?

### ISSUE THREAD

**Issue by adriancruceru** [artbycrunk/vscode-maya#19]
Hi

I'm using this extension but I only get the autocomplete for the command and no flags after the command, how do I get the flags working? Here's a small gif with what I get:
https://i.imgur.com/MLHUHHX.gif
I must be missing something

Thanks for any pointers

**Comment by artbycrunk** [comment]
Hi @adriancruceru you need to hit `Ctrl+Spacebar` once for the autocomplete to show extra details.

**Comment by adriancruceru** [comment]
It works nicely.
Great extension.

**Comment by artbycrunk** [comment]
Cool, thanks
