### ISSUE TITLE
Maya code send pythone

### ISSUE THREAD

**Issue by TTomoTT** [artbycrunk/vscode-maya#2]
Hi 
It looks like in maya code "Send Python to Maya" doesnt work. On other hand "Send MEL to Maya works" . Do you know maybe for any workarond or fix ?

Thank you

**Comment by artbycrunk** [comment]
Hi @TTomoTT do you have some output in the log?

**Comment by TTomoTT** [comment]
Sorry. It works perfectly. It was mine beginers mistake.

sub, 13. tra 2019. 13:05 Savio Fernandes <notifications@github.com> je
napisao:
