### ISSUE TITLE
possible to expose a user definable setting to send to port other than 7001?

### ISSUE THREAD

**Issue by jinchoung** [artbycrunk/vscode-maya#22]
hi,

great extension! thanks!

i ran into an issue where trying to open port 7001 resulted in a windows 10013 error. turns out that it could have been antivir or firewalls but it ended up being that a sentinel keys server program was also occupying ports 7001 and 7002 to do its thing for one of my graphics programs using the sentinel system (maybe fusion?).

anyway, if i disable the key server, i can use your extension to send stuff to maya no problem. but i was wondering if it was possible to allow the user to define other ports in your extension since all kinds of hardware and software can take ownership of ports and not leave it available to maya.

anyway, thanks again for a great extension!

jin

**Comment by artbycrunk** [comment]
hi @jinchoung 
Yes its common that ports could be already opened by other tools,

The port in vscode-maya is configurable via the vscode settings.

![image](https://user-images.githubusercontent.com/1092099/97512557-c7204f80-19c4-11eb-9c7f-0a55efd3d99b.png)

Just be sure to open the same port in Maya as well.

**Comment by jinchoung** [comment]
aha! i just found that! thank you much!

jin
