### ISSUE TITLE
not running code properly

### ISSUE THREAD

**Issue by miklem** [artbycrunk/vscode-maya#3]
Hi! I have a simple code, that suppose to create a set of references. 
Once I run it directly in Maya or from sublime it works fine, but once I send it through VScode it doesn't create a reference although part of the code run well. 
[turntable.zip](https://github.com/artbycrunk/vscode-maya/files/3149875/turntable.zip)

**Comment by artbycrunk** [comment]
Hey @miklem, thanks for the feedback, what's the version of Maya you are using?

**Comment by miklem** [comment]
Hi!
2018.3  and python is 2.7.11

**Comment by artbycrunk** [comment]
I have pushed out a new update to the extension, version 1.0.0
can you update and then check if you still have issues...

Note that you now only need to open one common port for both python and mel code, by doing this
```
commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;
```

**Comment by miklem** [comment]
Works fine! Thank you so much.
