### ISSUE TITLE
Is there any way to use this extension at Maya start up?

### ISSUE THREAD

**Issue by FrankShao832** [artbycrunk/vscode-maya#30]
**Is your feature request related to a problem? Please describe.**
This extension works. But need to setup every time new session.

**Describe the solution you'd like**
If I don't need to manually run the line of code to open port every time open a new Maya or vs code session that will be great!

If there already a way to do it like setup a user setup file etc. please let me know.

**Comment by artbycrunk** [comment]
Hi @FrankShao318 
If you are familiar with the userSetup.mel, then you can add the following command to it
`commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;`
This will ensure that the port is open on Maya startup

**Comment by FrankShao832** [comment]
Hi @artbycrunk ,
Thanks for the quick reply!
Previously, I was using Pycharm and had a userSetup.py file which setup the commandPort 4434 for Pycharm.
Can I have both of them work together? Or I can only have one work in the folder?

**Comment by artbycrunk** [comment]
@FrankShao318 yeah both should be able to work together, as long as the vscode-maya extension is made aware of what port number you want to use.

**Comment by FrankShao832** [comment]
@artbycrunk  Thank you very much!
