### ISSUE TITLE
Maya command highlighting within .py

### ISSUE THREAD

**Issue by PolyShifter** [artbycrunk/vscode-maya#4]
Hi there I'm a newb when it comes to code writing and same to Visual Studio Code. I was wondering if there is a way to be working in a python script and still get the highlighting and the mel definitions and stuff. For me it only works inside a mel command. I'm sure there's a way and I'm just a fool for not finding it. I've tried googling it and I can't figure out the right question to ask. Sorry if this is posted in the wrong spot!

**Comment by artbycrunk** [comment]
hey @PolyShifter, 
do you have an example of the code where you write MEL inside a python file??

Visual Studio Code will switch context based on the currently detected language of the file, 
which I'm guessing is set to Python, in which case there will be no autocomplete or highlighting on MEL code unless you force set the file`s language to MEL.

**Comment by PolyShifter** [comment]
Oh darn! Okay, I was hoping to kind of add the MEL like... errr definitions to VSC's python definitions or something like that. Like, where I can see both when I'm typing in .py file.
An example of python writing would be as follows:
import maya.cmds as mc


def replace_objects_single(*args):
    ###Search and replace objects and match hierarchy and name.
    inputText=''
    replaceObjectsUI = mc.promptDialog(title="Replace Objects with new Object",
                        message="Enter New Asset Name:",
                        button=['OK','Cancel'],
                        defaultButton='OK',
                        cancelButton='Cancel',
                        dismissString='Cancel')
    if replaceObjectsUI == 'OK':
        inputText=mc.promptDialog(query=True, text=True)

    selected = mc.ls(selection=True)
    for item in selected:
        mc.select(inputText, replace=True)
        mc.duplicate(returnRootsOnly=True, upstreamNodes=True, renameChildren=True)
        newObj = mc.ls(selection=True)
        childrenOfSelected = mc.listRelatives(mc.ls(sl=True), allDescendents=True)
        for child in childrenOfSelected:
            if mc.nodeType(child) == 'mesh':
                mc.select(child, replace=True)
                transNodeName=mc.listRelatives(parent=True)
                transNodeName= ''.join(transNodeName)
                newShapeName = transNodeName + 'Shape'
                newShapeName
                mc.rename(child, newShapeName)
        mc.select(clear=True)
        mc.select(item, replace=True)
        mc.select(newObj, toggle=True)
        mc.pointConstraint(offset=[0,0,0], weight=1)
        mc.orientConstraint(offset=[0,0,0], weight=1)
        mc.scaleConstraint(offset=[1,1,1], weight=1)
        mc.select(clear=True)
        mc.select(item, replace=True)
        mc.delete()
I'm not the cleanest coder by any means haha but this is pretty standard python/mel coding.

**Comment by PolyShifter** [comment]
Oh darn! Okay, I was hoping to kind of add the MEL like... errr definitions
to VSC's python definitions or something like that. Like, where I can see
both when I'm typing in .py file.
An example of python writing would be as follows:
import maya.cmds as mc
def replace_objects_single(*args):
    ###Search and replace objects and match hierarchy and name.
    inputText=''
    replaceObjectsUI = mc.promptDialog(title="Replace Objects with new
Object",
                        message="Enter New Asset Name:",
                        button=['OK','Cancel'],
                        defaultButton='OK',
                        cancelButton='Cancel',
                        dismissString='Cancel')
    if replaceObjectsUI == 'OK':
        inputText=mc.promptDialog(query=True, text=True)

    selected = mc.ls(selection=True)
    for item in selected:
        mc.select(inputText, replace=True)
        mc.duplicate(returnRootsOnly=True, upstreamNodes=True,
renameChildren=True)
        newObj = mc.ls(selection=True)
        childrenOfSelected = mc.listRelatives(mc.ls(sl=True), allDescendents
=True)
        for child in childrenOfSelected:
            if mc.nodeType(child) == 'mesh':
                mc.select(child, replace=True)
                transNodeName=mc.listRelatives(parent=True)
                transNodeName= ''.join(transNodeName)
                newShapeName = transNodeName + 'Shape'
                newShapeName
                mc.rename(child, newShapeName)
        mc.select(clear=True)
        mc.select(item, replace=True)
        mc.select(newObj, toggle=True)
        mc.pointConstraint(offset=[0,0,0], weight=1)
        mc.orientConstraint(offset=[0,0,0], weight=1)
        mc.scaleConstraint(offset=[1,1,1], weight=1)
        mc.select(clear=True)
        mc.select(item, replace=True)
        mc.delete()
I'm not the cleanest coder by any means haha but this is pretty standard
python/mel coding.

**Comment by artbycrunk** [comment]
Firstly this is not MEL, it is all python. 
For the autocomplete to work you need to do this... 
https://github.com/artbycrunk/maya-completion

**Comment by PolyShifter** [comment]
Omg I even double posted. Sorry about that.

Yeah I knew it was python, but I'm using maya commands within, so I didn't really know how to word my question properly. Thanks for helping me out! This is fantastic!!

**Comment by artbycrunk** [comment]
No problem, glad to help.
Closing this issue, let me know if you have any other concerns.
