### ISSUE TITLE
can't send Non-ASCII character, even though they're in the comments

### ISSUE THREAD

**Issue by g2mXagent** [artbycrunk/vscode-maya#5]
code like here:
`print("python code") # 這是中字`
send python code to maya, error in maya script editor:
`# Error: line 1: SyntaxError: file <maya console> line 1: Non-ASCII character '\xe6' in file C:/Users/Lee/AppData/Local/Temp/MayaCode.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details #`
maybe its the solution:
**when send code to maya, temporarily remove all comments.**

**Comment by artbycrunk** [comment]
hi @g2mXagent this is an interesting issue.
let me test it at my end and see how to solve.

**Comment by artbycrunk** [comment]
Hi @g2mXagent, this is fixed in the latest version 1.0.1

**Comment by g2mXagent** [comment]
thank you! already update.

Savio Fernandes <notifications@github.com> 于2019年6月6日周四 下午11:29写道：
