### ISSUE TITLE
When sending python code to Maya and there are execution errors, is it possible to highlight the offending lines back in Code?

### ISSUE THREAD

**Issue by digitalmonkey** [artbycrunk/vscode-maya#7]
When I send my Python scripts to Maya, I typically get some syntax errors initially - is there a way we can get the feedback out of Maya and highlight the offending lines in Code?

**Comment by artbycrunk** [comment]
hi @digitalmonkey,
The information is available in VSC`s Output window under Maya.
![image](https://user-images.githubusercontent.com/1092099/62763353-e8de9f80-babd-11e9-860b-daacb9fa35b2.png)

**Comment by digitalmonkey** [comment]
Thanks!
