### ISSUE TITLE
Print statements not appearing in MayaCharm

### ISSUE THREAD

**Issue by kalkoby** [artbycrunk/vscode-maya#8]
I want to know if there is a way to print the translation information from Maya that I code in Visual Studio Code.  I was able to send command to Maya to create some geometry stuffs.  I do not see any output from  print statements.  If I were to run Python embedded in Maya, I would see the print statements.   But not the external editor of VSC,  your advice will be appreciated.  I think the problem is that I was not able to receiving info from Maya to VSC but   I was able to send information to Maya.

Thanks in advance

**Comment by artbycrunk** [comment]
Hi @kalkoby,

The information is available in VSC`s Output window under Maya.

![image](https://user-images.githubusercontent.com/1092099/62763100-4e7e5c00-babd-11e9-9218-9deaa5fb5d90.png)

**Comment by kalkoby** [comment]
Hello Savio,


Thank you so much for your reply.  Setting up environment always have been so difficult for me.   I am good at coding but I need to set up environment properly before I could go ahead smoothly.

That is what I want like you have.

#1 I finally was able to send Python to Maya as shown on the left side.  However I kept getting error on the right side.  It would be nice if I could do both.

Number 2 :  I also am struggling to import the custom python program.  How could I do on VSC?


Thanks in advance,  Karen
________________________________

**Comment by kalkoby** [comment]
To make things easier :  I think I need to find a way to point to correct pylint in VSC.

[cid:ce0a1744-48d7-4495-a0a6-a5cf5cbda39c]
________________________________

**Comment by artbycrunk** [comment]
Hey Karen, 
seems like you are having multiple issues, which are a bit hard to understand here..
maybe you can better explain on a quick chat here.. 
https://gitter.im/vscode-maya/vscode-maya

And regarding pylint, if you pip install pylint in your current python environment, 
and add pylint to your vscode settings, it should currently be activated.

**Comment by artbycrunk** [comment]
@kalkoby are you still having issues?

**Comment by kalkoby** [comment]
Hello!  Sorry I did not reply back to you.     I still have an issue but I am using PyCharm.  For my debugging, I have to use print statements.  I wish there is an interactive debugging between Maya and Python.    So far, I have'nt had a luck.

Karen
________________________________

**Comment by jdily** [comment]
Hi I am not sure why I can not see the print message under VS code output window under Maya?
I follow the code above, but got no printed message.
Do you know how can I get the message?
![image](https://user-images.githubusercontent.com/304749/155713275-477978b0-5c69-464c-9271-ae60220ee3b6.png)
